# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convo', '0003_auto_20170415_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
