# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('convo', '0004_auto_20170415_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='convo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
