# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 19:15
from __future__ import unicode_literals

import convo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convo', '0005_convo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='content',
            field=models.CharField(max_length=200, validators=[convo.models.validate_content]),
        ),
    ]
