# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convo', '0009_convo_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='convo',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Is a reply?'),
        ),
    ]
